table ecommerce_data
	lineageTag: 925304a9-3339-4070-81df-1aee5de98627

	measure 'YTD Sales' = TOTALYTD(SUM(ecommerce_data[sales_per_order]),'Calendar'[Date])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 65a1913b-772e-4ca8-8f33-460a0ae12fc1

	measure 'PYTD Sales' = CALCULATE(sum(ecommerce_data[sales_per_order]),DATESYTD(SAMEPERIODLASTYEAR('Calendar'[Date])))
		lineageTag: 8bc81001-3520-4510-9d00-42e5767c7596

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Sales' = ([YTD Sales] -[PYTD Sales])/[PYTD Sales]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9451132b-e243-40f2-ba72-a8c6d76668c1

	measure 'Sales Icon' = ```
			var positive_icon=UNICHAR(9650) 
			            var negative_icon= UNICHAR(9660)
			                var result= IF([YoY Sales]>0,positive_icon,negative_icon)
			                return result
			```
		lineageTag: 9ad2ff29-ef1d-493d-b7de-44c1ce421445

	measure 'SALES ICON COLOUR' = ```
			IF([YoY Sales]>0,"Green","Red") 
			```
		lineageTag: 25749fa7-1af0-4077-b4c7-208479cfa523

	measure 'sales colour' = IF([YoY Sales]>0,"Green","Red")
		lineageTag: bf9c36b1-0066-4067-9ec3-0764e73b8597

	measure 'YTD Profit' = TOTALYTD(SUM(ecommerce_data[profit_per_order]),'Calendar'[Date])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4effb2a2-4550-43a6-8845-333909e7d2b9

	measure 'PYTD Profit' = CALCULATE(sum(ecommerce_data[profit_per_order]),DATESYTD(SAMEPERIODLASTYEAR('Calendar'[Date])))
		lineageTag: 3172e4ee-5252-48c4-b674-3b7542554a9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Profit' = ([YTD Profit] -[PYTD Profit])/[PYTD Profit]
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: b3d0fc58-4877-4904-8d0e-87fb3278270a

	measure 'Profit Icon' = ```
			var positive_icon=UNICHAR(9650) 
			            var negative_icon= UNICHAR(9660)
			                var result= IF([YoY Profit]>0,positive_icon,negative_icon)
			                return result
			```
		lineageTag: 12363f35-f5c3-4a51-937a-121bb536c556

	measure 'PROFIT ICON COLOUR' = IF([YoY Profit]>0,"Green","Red")
		lineageTag: 0731ae44-02c5-44b4-8af4-7e6cff0aa2ea

	measure 'YTD Quantity' = TOTALYTD(SUM(ecommerce_data[order_quantity]),'Calendar'[Date])
		formatString: 0.0
		lineageTag: 1c1bb81d-7af2-4d35-9797-eaa4227c8a55

	measure 'PYTD Quantity' = CALCULATE(sum(ecommerce_data[order_quantity]),DATESYTD(SAMEPERIODLASTYEAR('Calendar'[Date])))
		formatString: 0
		lineageTag: d9a54d5d-75f0-4ba4-b20a-ba3d9ba03551

	measure 'YoY Quantity' = ([YTD Quantity] -[PYTD Quantity])/[PYTD Quantity]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 84fe83f8-90a3-404c-9ba7-9dd633d627f4

	measure 'Quantity Icon' = ```
			var positive_icon=UNICHAR(9650) 
			            var negative_icon= UNICHAR(9660)
			                var result= IF([YoY Quantity]>0,positive_icon,negative_icon)
			                return result
			```
		lineageTag: cc23d476-c651-45f2-a35a-d1d1d9041639

	measure 'QUANTITY ICON COLOUR' = ```
			IF([YoY Quantity]>0,"Green","Red") 
			```
		lineageTag: c74dc997-6f9f-434f-9c0b-3fcdcdb38506

	measure 'Profit Margin' = SUM(ecommerce_data[profit_per_order])/SUM(ecommerce_data[sales_per_order])
		lineageTag: a5486f54-0a33-4fd2-a27b-10ddbfd1dd65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Profit Margin' = TOTALYTD([Profit Margin],'Calendar'[Date])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a2ed25b3-a114-4734-8627-1d42bf98806f

	measure 'PYTD Profit Margin' = CALCULATE([Profit Margin],DATESYTD(SAMEPERIODLASTYEAR('Calendar'[Date])))
		lineageTag: 27bfae48-1ab3-491a-abd4-dfdaaadf8ac3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Profit Margin' = ([YTD Profit Margin] -[PYTD Profit Margin])/[PYTD Profit Margin]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 01d5b404-5881-401f-910e-4e2de2008cb6

	measure 'Profit Margin Icon' = ```
			var positive_icon=UNICHAR(9650) 
			            var negative_icon= UNICHAR(9660)
			                var result= IF([YoY Profit Margin]>0,positive_icon,negative_icon)
			                return result
			```
		lineageTag: 0bbc2c42-67ab-43d3-9389-38f95b165832

	measure 'Profit Margin colour' = IF([YoY Profit Margin]>0,"Green","Red")
		lineageTag: 6fb5e779-f0db-4ec8-9207-d440f0503159

	column customer_id
		dataType: string
		lineageTag: 754937c5-8d63-493a-b524-4364890e5325
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_first_name
		dataType: string
		lineageTag: d7e9b425-b53c-4a82-a7e4-f753d486c19a
		summarizeBy: none
		sourceColumn: customer_first_name

		annotation SummarizationSetBy = Automatic

	column customer_last_name
		dataType: string
		lineageTag: 1403778d-ff58-4d9e-9716-e9d0baa49f8b
		summarizeBy: none
		sourceColumn: customer_last_name

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 02082b2f-1130-4c75-93a5-60406c8b6243
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: ca8ce9b8-1709-49c3-ba78-502975baff02
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column customer_segment
		dataType: string
		lineageTag: 46d7d39e-7bbe-416e-bc82-c88b179f6182
		summarizeBy: none
		sourceColumn: customer_segment

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 900c3eed-a27f-4dc2-bcb7-09867b35a5f8
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 99682acb-9c34-4cc2-aa98-9b2ab98db38a
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: 1eafeb0d-21cb-4c7e-a78f-4ab84cb669e2
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column customer_region
		dataType: string
		lineageTag: 502af1ac-2424-4a01-92c7-63823190b54b
		summarizeBy: none
		sourceColumn: customer_region

		annotation SummarizationSetBy = Automatic

	column delivery_status
		dataType: string
		lineageTag: e8994577-ae57-41ed-862a-c3f8e8806aa1
		summarizeBy: none
		sourceColumn: delivery_status

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 15745a5b-dcfe-4906-8ef6-cf8797afdce0
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_id
		dataType: string
		lineageTag: 854d6f6c-9865-4bde-9ade-584b48ab9b53
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column ship_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f832a461-47b8-4bc8-8b56-0493e5e8b234
		summarizeBy: none
		sourceColumn: ship_date

		variation Variation
			isDefault
			relationship: 8b6f614e-1b28-447d-a6ae-707f06d6cd16
			defaultHierarchy: LocalDateTable_d55a8b0c-2bad-4422-962e-98ab1944e714.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column shipping_type
		dataType: string
		lineageTag: 58337c71-30d5-42a7-bce4-495fa5d71883
		summarizeBy: none
		sourceColumn: shipping_type

		annotation SummarizationSetBy = Automatic

	column days_for_shipment_scheduled
		dataType: int64
		formatString: 0
		lineageTag: 8d5effca-b6a3-4592-9774-170afa0cb419
		summarizeBy: sum
		sourceColumn: days_for_shipment_scheduled

		annotation SummarizationSetBy = Automatic

	column days_for_shipment_real
		dataType: int64
		formatString: 0
		lineageTag: 670572cf-585a-478a-b5ca-908f5b0c0c7e
		summarizeBy: sum
		sourceColumn: days_for_shipment_real

		annotation SummarizationSetBy = Automatic

	column order_item_discount
		dataType: double
		lineageTag: b10c60fa-af99-4706-8e6d-31684f6a365e
		summarizeBy: sum
		sourceColumn: order_item_discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_per_order
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2db8359e-93c0-4185-b41e-3ab86d5c3657
		summarizeBy: sum
		sourceColumn: sales_per_order

		annotation SummarizationSetBy = Automatic

	column order_quantity
		dataType: int64
		formatString: 0
		lineageTag: 5dcb5f08-2dbd-4146-8c21-e61ca9c27cae
		summarizeBy: sum
		sourceColumn: order_quantity

		annotation SummarizationSetBy = Automatic

	column profit_per_order
		dataType: double
		lineageTag: cbcc560e-c314-41c4-8526-49c513ac3295
		summarizeBy: sum
		sourceColumn: profit_per_order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ecommerce_data = m
		mode: import
		source =
				let
				    Source = Sql.Database("ARUNANDU", "Ecommerce_database"),
				    dbo_ecommerce_data = Source{[Schema="dbo",Item="ecommerce_data"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_ecommerce_data,{{"category_name", "Category"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

